name: Hair Website CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t hair-site .

    - name: Run container
      run: docker run -d -p 8080:80 hair-site

    - name: Wait for container to start
      run: sleep 10

    - name: Check logs (debug step)
      run: docker logs web

    - name: Test website
      run: curl --retry 5 --retry-delay 3 http://localhost:8080

    - name: Stop container
      run: docker stop web